/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminSideMenu: typeof import('./src/components/admin/AdminSideMenu.vue')['default']
    DataGrid: typeof import('./src/components/common/DataGrid.vue')['default']
    FacebookSyncSection: typeof import('./src/components/integrations/FacebookSyncSection.vue')['default']
    FilterBar: typeof import('./src/components/dashboard/FilterBar.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KwaiManager: typeof import('./src/components/integrations/KwaiManager.vue')['default']
    KwaiModal: typeof import('./src/components/integrations/KwaiModal.vue')['default']
    LayoutSettings: typeof import('./src/components/layout/LayoutSettings.vue')['default']
    MetaAdsSection: typeof import('./src/components/integrations/MetaAdsSection.vue')['default']
    MetricCard: typeof import('./src/components/dashboard/MetricCard.vue')['default']
    PaymentChart: typeof import('./src/components/dashboard/PaymentChart.vue')['default']
    PixelManager: typeof import('./src/components/integrations/PixelManager.vue')['default']
    ReusableList: typeof import('./src/components/common/ReusableList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/layout/SideMenu.vue')['default']
    Table: typeof import('./src/components/common/Table.vue')['default']
    UtmSection: typeof import('./src/components/integrations/UtmSection.vue')['default']
    WebhookApiModal: typeof import('./src/components/integrations/WebhookApiModal.vue')['default']
    WebhookModal: typeof import('./src/components/integrations/WebhookModal.vue')['default']
    WebhooksSection: typeof import('./src/components/integrations/WebhooksSection.vue')['default']
  }
}
